language: php
php:
  - 7.2
addons:
  ssh_known_hosts: gcp.puckwang.com
cache:
  directories:
    - $HOME/.composer/cache
install:
  - composer install
script:
  - ./vendor/bin/phpunit
before_deploy:
  - eval "$(ssh-agent -s)"
  - composer global require laravel/envoy
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - echo "SERVER_NAME=$SERVER_NAME" >> .env
  - echo "SLACK_CHANNEL=$SLACK_CHANNEL" >> .env
  - echo "SLACK_HOOK_URL=$SLACK_HOOK_URL" >> .env
deploy:
  - provider: script
    skip_cleanup: true
    script: ~/.composer/vendor/bin/envoy run production-cms --branch=master
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ~/.composer/vendor/bin/envoy run testing-cms --branch=develop
    on:
      branch: develop
